### ISSUE TITLE
Theme icon missing on mac

### ISSUE THREAD

**Issue by marciodasilva** [rm-code/base16-ocean-dark-ui#1]
Hello,
I am using the Base 16 Ocean Dark (UI Theme and Syntax Theme) on Mac (10.9.5), which is missing the file icons. Is there an additional configuration needed in order to display the icons?

Thanks in advance,

Marcio

**Comment by rm-code** [comment]
Hello,

The file-icons are provided by a separate package: https://github.com/DanBrooker/file-icons

I forgot about the file-icons when I took the screenshot for the theme. Sorry for the confusion!

Best wishes,
Robert

**Comment by marciodasilva** [comment]
Hi Robert, thanks for getting back to me. To be honest, I don't have a clue how to install the icon resource (files or package). Any help with the installation steps would be very appreciated.
Cheers to you,
Marcio

Date: Sat, 6 Jun 2015 07:56:46 -0700

**Comment by rm-code** [comment]
Open the Atom preferences (cmd + , or via the menu) and look for the install tab:

![screenshot 2015-06-07 09 09 25](https://cloud.githubusercontent.com/assets/11627131/8022981/fc729ef0-0cf4-11e5-95be-6f81e6eb4975.png)

Search for file-icons and the package should come up on the right (make sure it is the one by DanBrooker). Click on the install button on the right and that's it. 

![screenshot 2015-06-07 09 10 35](https://cloud.githubusercontent.com/assets/11627131/8022993/b3104504-0cf5-11e5-8b70-4fdfbeeddf1f.png)

---

The shorter way is to open your Terminal and enter `apm install file-icons` 

Hope that helps,
Robert

**Comment by marciodasilva** [comment]
Worked! Thank you very much.
Cheers to you,
Marcio

Date: Sun, 7 Jun 2015 00:16:27 -0700

**Comment by rm-code** [comment]
You are welcome!
